services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver-db
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: MiPassw0rd!
      MSSQL_PID: Express
    volumes:
      - ./message_sqlserver.sql:/tmp/message.sql:ro
      - ./insert_sqlserver.sql:/tmp/insert.sql:ro
      - ./init_sqlserver.sh:/tmp/init_sqlserver.sh:ro
    ports:
      - "1433:1433"
    networks:
      - sqlserver-network
    healthcheck:
      test: ["CMD-SHELL", "pgrep sqlservr"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  init-sqlserver:
    image: mcr.microsoft.com/mssql-tools:latest
    container_name: sqlserver-init
    depends_on:
      sqlserver:
        condition: service_healthy
    volumes:
      - ./message_sqlserver.sql:/tmp/message.sql:ro
      - ./insert_sqlserver.sql:/tmp/insert.sql:ro
      - ./init_sqlserver.sh:/tmp/init_sqlserver.sh:ro
    command: /bin/bash /tmp/init_sqlserver.sh
    networks:
      - sqlserver-network

networks:
  sqlserver-network:
    driver: bridge